* General

#+BEGIN_SRC emacs-lisp
(setq user-full-name "Ben Whitley"
      user-mail-address "dev@purplg.com")
#+END_SRC

Disables the extra line at the end of file
#+BEGIN_SRC emacs-lisp
(setq require-final-newline nil)
#+END_SRC

Show the class/function location of the point in the file
#+BEGIN_SRC emacs-lisp
(which-function-mode)
#+END_SRC

This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type 'relative)
#+END_SRC


Save recent files every time a new file is 'found'
#+begin_src emacs-lisp
;(add-hook! 'find-file-hook #'recentf-save-list)
#+end_src

Save recent files every 5 minutes
#+begin_src emacs-lisp
;(run-at-time (current-time) (* 5 60) 'recentf-save-list)
#+end_src

* Font
Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:

+ `doom-font'
+ `doom-variable-pitch-font'
+ `doom-big-font' -- used for `doom-big-font-mode'; use this for
  presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:
setq doom-font (font-spec :family "monospace" :size 14))

#+BEGIN_SRC emacs-lisp
(setq doom-font (font-spec :family "Source Code Pro" :size 14))
#+END_SRC

* Theme
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-horizon)
#+END_SRC

* Key bindings
** Find file

#+BEGIN_SRC emacs-lisp
(map! :desc "File at point"
 :leader
 :n "f h"
 'find-file-at-point )
#+END_SRC

** LSP
#+BEGIN_SRC emacs-lisp
(defun lsp-import-and-format ()
  (interactive)
  (lsp-organize-imports)
  (lsp-format-buffer))

(map! :desc "LSP Format"
 :leader
 :n "c f"
 'lsp-import-and-format)
#+END_SRC

** Evil tweaks

Scroll the entire buffer up or down when ^ is held
#+BEGIN_SRC emacs-lisp
(defun scroll-page-line-down ()
  (interactive)
  (evil-scroll-line-down 1)
  (evil-next-line 1))

(defun scroll-page-line-up ()
  (interactive)
  (evil-scroll-line-up 1)
  (evil-next-line -1))

(map! :ni "^j" 'scroll-page-line-down)
(map! :ni "^k" 'scroll-page-line-up)
#+END_SRC

Clear all find matches
#+BEGIN_SRC emacs-lisp
(map! :desc "Clear search highlight"
 :leader
 :n "s c"
 'evil-ex-nohighlight )
#+END_SRC

Fold all folds at level 2... weird hack for some project I worked on a long time ago. Maybe try a different keybind or allow it to get an integer argument?
#+BEGIN_SRC emacs-lisp
(defun +fold/close-all-level-2 ()
  (interactive)
  (+fold/close-all 2))

(map!
 :leader
 :n "z m"
 '+fold/close-all-level-2)
#+END_SRC

#+begin_src emacs-lisp
(map!
 :n "C-M-D"
 'evil-multiedit-match-all)
#+end_src

** Journal
#+BEGIN_SRC emacs-lisp
(map! :desc "Journal"
  :leader
  :n "j")

(map! :desc "New entry"
  :leader
  :n "j n"
  'org-journal-new-entry)

(map! :desc "Next journal"
  :leader
  :n "j l"
  'org-journal-next-entry)

(map! :desc "Previous journal"
  :leader
  :n "j h"
  'org-journal-previous-entry)
#+END_SRC

** Applications

#+BEGIN_SRC emacs-lisp
(map! :desc "Open terminal"
 :leader
 :n "o t"
 'eshell )

(map! :desc "Applications"
 :leader
 :n "a" )
#+END_SRC

* Packages
** persp-mode
Prevent creating new workspaces when opening new emacs-client
Found here: [[https://github.com/hlissner/doom-emacs/issues/1949][hlissner/doom-emacs#1949 {REQUEST} No new workspace created on incoming emacs...]]
#+BEGIN_SRC emacs-lisp
(after! persp-mode
  (setq persp-emacsclient-init-frame-behaviour-override "main"))
#+END_SRC
** which-key
#+BEGIN_SRC emacs-lisp
(setq which-key-idle-delay 0.3)
#+END_SRC
** org-mode

Set the default location of org files
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/.org/")
#+END_SRC

*** Roam
#+BEGIN_SRC emacs-lisp
(use-package! org-journal
  :custom
  (org-journal-date-prefix "#+TITLE: ")
  (org-journal-file-format "%Y-%m-%d.org")
  (org-journal-dir "~/.org-roam")
  (org-journal-date-format "%A, %d %B %Y"))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package! org-roam
  :commands (org-roam-insert org-roam-find-file org-roam)
  :init
  (setq org-roam-directory "~/.org")
  (setq org-roam-graph-viewer "/usr/bin/open")
;;  (map! :leader
;;        :prefix "n"
;;        :desc "Org-Roam-Insert" "i" #'org-roam-insert
;;        :desc "Org-Roam-Find"   "/" #'org-roam-find-file
;;        :desc "Org-Roam-Buffer" "r" #'org-roam)
  :config
  (org-roam-mode +1))
#+END_SRC
*** Capture Templates

#+begin_src emacs-lisp :results silent
(setq +org-capture-todo-file "project.org")
(setq org-capture-templates
      '(("w" "Work"
         entry (file+headline "~/.org/Work.org" "General")
         "* TODO %?\n %i\n")
        ("p" "Current project"
         entry (file+headline +org-capture-project-todo-file "Tasks")
        "* TODO %?\n%i\n%a" :prepend t)))
#+end_src

** lsp-mode
#+BEGIN_SRC emacs-lisp
(after! lsp-mode
    :config
    (setq! lsp-enable-file-watchers nil))
#+END_SRC
** company-mode

#+BEGIN_SRC emacs-lisp
(after! company
  :config
  (setq! company-idle-delay 0
         company-minimum-prefix-length 3))
#+END_SRC

** projectile
https://github.com/ericdanan/counsel-projectile

This excludes a lot of files I never want to edit in emacs from the file finder.
Mostly just Unity stuff

#+BEGIN_SRC emacs-lisp :tangle no
(after! counsel
 (setq counsel-find-file-ignore-regexp "\\(?:^[#.]\\)\\|\\(?:[#~]$\\)\\|\\(?:^Icon?\\)\\|\\(?:.meta$\\)\\|\\(?:.asset$\\)\\|\\(?:.prefab$\\)"))
#+END_SRC
** treemacs
https://github.com/Alexander-Miller/treemacs#projects-and-workspaces

Also exlucdes some Unity files from treemacs

#+BEGIN_SRC emacs-lisp
(after! treemacs
  :config
  (defun treemacs-ignore-unity (filename absolute-path)
    (or (string-suffix-p ".meta" filename t)
        (string-suffix-p ".asset" filename t)))
  (add-to-list 'treemacs-ignored-file-predicates #'treemacs-ignore-unity)
  (treemacs-follow-mode))
#+END_SRC

** deft
#+BEGIN_SRC emacs-lisp
(after! deft
;;  :bind
;;  ("C-c n d" . deft)
  (setq deft-recursive nil)
  (setq deft-use-filter-string-for-filename t)
  (setq deft-default-extension "org")
  (setq deft-directory "~/.org"))
#+END_SRC
#** undo-fu
#
##+begin_src emacs-lisp
#(add-hook 'evil-local-mode-hook 'turn-on-undo-tree-mode)
##+end_src
