;;; --- -*- lexical-binding: t; -*-

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq straight-disable-native-compile nil)

(straight-use-package 'which-key)
(straight-use-package 'general)
(straight-use-package 'undo-fu)
(straight-use-package 'undo-fu-session)
(straight-use-package 'evil)
(straight-use-package 'evil-surround)
(straight-use-package 'evil-collection)
(straight-use-package 'vertico)
(straight-use-package 'consult)
(straight-use-package 'consult-lsp)
(straight-use-package 'marginalia)
(straight-use-package 'orderless)
(straight-use-package 'savehist)
(straight-use-package 'embark)
(straight-use-package 'dashboard)
(straight-use-package 'helpful)
(straight-use-package 'doom-themes)
(straight-use-package 'page-break-lines)
(straight-use-package 'persp-mode)
(straight-use-package 'expand-region)
(straight-use-package 'company)
(straight-use-package 'rainbow-delimiters)
(straight-use-package 'parinfer-rust-mode)
(straight-use-package 'emr)
(straight-use-package 'package-lint)
(straight-use-package 'flycheck-package)
(straight-use-package 'flycheck)
(straight-use-package 'magit)
(straight-use-package 'git-gutter)
(straight-use-package 'highlight-indent-guides)
(straight-use-package 'lsp-mode)
(straight-use-package 'lsp-ui)
(straight-use-package 'outshine)
(straight-use-package 'treemacs)
(straight-use-package 'treemacs-all-the-icons)
(straight-use-package 'project)
(straight-use-package 'rustic)
(straight-use-package 'restclient)
(straight-use-package 'yasnippet-snippets)
(straight-use-package 'yasnippet)
(straight-use-package 'yaml-mode)
(straight-use-package 'pass)
(straight-use-package 'eshell)
(straight-use-package 'elfeed)
(straight-use-package 'nov)
(straight-use-package `(plz :type git :host github :repo "alphapapa/plz.el"))
(straight-use-package `(ement :type git :host github :repo "alphapapa/ement.el"))
(straight-use-package 'exec-path-from-shell)
(straight-use-package 'alert)
(straight-use-package 'telega)
(straight-use-package 'tramp)
(straight-use-package `(hass :local-repo "~/code/elisp/hass"))

(provide 'pg-packages)
